# Generated by Django 4.0.2 on 2022-02-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=1000)),
                ('avatar', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
    ]
