# Generated by Django 4.0.2 on 2022-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_candidates_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='avatar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='login',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
